### ISSUE TITLE
Missing container?

### ISSUE THREAD

**Issue by kubenetic** [freegyes/codeberry-node#1]
Hi guys!
I've cloned your repo, and start it based on the readme file. Am I blind, or there is really no 'codeberry-dev' named docker container? I did not found it neither at git repo nor at docker hub. I've became this: 
./development.sh 
/home/xxx/codeberry-node/backend-codebase/scripts/../frontend-codebase
Error response from daemon: No such container: codeberry-dev
Error response from daemon: No such container: codeberry-dev

Otherwise, the node:5.0 docker container downloaded successfully, and I can started it too. After all I've started the node:5.0 container the node server ran in good order.

Sorry for my english ;)
Üdv és jó munkát :-)

**Comment by freegyes** [comment]
Hi!

The error message is a bit misleading. It tries to stop and remove the container if it's running:

```
docker stop ${CONTAINER_NAME}  
docker rm ${CONTAINER_NAME}
```

Obviously for the first time it won't find any running instances yet thus it gives back this error.

It should be corrected in a later version.

**Comment by kubenetic** [comment]
Yepp, I know this, that at the first run there will be no docker container. But after the development.sh is finished I not found the codeberry-dev container, the `docker images` command not listing it. Only the node:5.0 container installed, and when I start it directly then start the localhost. Or is it normal?

**Comment by freegyes** [comment]
It is perfectly normal. This script fires up the `node:5.0` image.
(Having an own Dockerfile or image would prevent the mounting of local files that would really slow down the development process; the `-v` flag doesn't work there.)

**Comment by kubenetic** [comment]
Ohh, I see. Sorry for the false alarm.
